-- --------------------------------------------------------
-- Хост:                         127.0.0.1
-- Версия сервера:               5.5.23 - MySQL Community Server (GPL)
-- ОС Сервера:                   Win64
-- HeidiSQL Версия:              9.3.0.4984
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
-- Дамп данных таблицы omdb.movie: ~0 rows (приблизительно)
DELETE FROM `movie`;
/*!40000 ALTER TABLE `movie` DISABLE KEYS */;
INSERT INTO `movie` (`IMDB_ID`, `CREATED_AT`, `MODIFIED_AT`, `ACTORS`, `AWARDS`, `COUNTRY`, `DIRECTOR`, `GENRE`, `IMDB_RATING`, `IMDB_VOTES`, `LANGUAGE`, `METASCORE`, `PLOT`, `POSTER`, `RATED`, `RELEASED`, `RESPONSE`, `RUNTIME`, `TITLE`, `TYPE`, `WRITER`, `YEAR`) VALUES
	('tt0074695', '2017-02-16 16:59:49', '2017-02-16 17:00:11', 'James Coburn, Maximilian Schell, James Mason, David Warner', '2 wins.', 'UK, West Germany', 'Sam Peckinpah', 'Drama, War', '7.5', '20,962', 'English, Russian, French, German', 'N/A', 'A German commander places a squad in extreme danger after its Sergeant refuses to lie for him.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BZDY4ZjY1MmYtYmQzZC00Y2ZmLWFhOGYtODlhMzA4NjU2NTdjXkEyXkFqcGdeQXVyMjI4MjA5MzA@._V1_SX300.jpg', 'R', '08 Mar 1977', 'True', '119 min', 'Cross of Iron', 'movie', 'Julius J. Epstein (screenplay), Walter Kelley (screenplay), James Hamilton (screenplay), Willi Heinrich (based on the book by)', '1977'),
	('tt0095953', '2017-02-17 13:25:25', NULL, 'Dustin Hoffman, Tom Cruise, Valeria Golino, Gerald R. Molen', 'Won 4 Oscars. Another 22 wins & 21 nominations.', 'USA', 'Barry Levinson', 'Drama', '8.0', '394,222', 'English, Italian', '65', 'Selfish yuppie Charlie Babbitt\'s father left a fortune to his savant brother Raymond and a pittance to Charlie; they travel cross-country.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMzVjNzI4NzYtMjE4NS00M2IzLWFkOWMtOTYwMWUzN2ZlNGVjL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'R', '16 Dec 1988', 'True', '133 min', 'Rain Man', 'movie', 'Barry Morrow (story), Ronald Bass (screenplay), Barry Morrow (screenplay)', '1988'),
	('tt0096895', '2017-02-16 21:27:48', '2017-02-17 13:23:23', 'Michael Keaton, Jack Nicholson, Kim Basinger, Robert Wuhl', 'Won 1 Oscar. Another 9 wins & 22 nominations.', 'USA, UK', 'Tim Burton', 'Action, Adventure', '7.6', '277,267', 'English, French', '69', 'The Dark Knight of Gotham City begins his war on crime with his first major enemy being the clownishly homicidal Joker.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTYwNjAyODIyMF5BMl5BanBnXkFtZTYwNDMwMDk2._V1_SX300.jpg', 'PG-13', '23 Jun 1989', 'True', '126 min', 'Batman', 'movie', 'Bob Kane (Batman characters), Sam Hamm (story), Sam Hamm (screenplay), Warren Skaaren (screenplay)', '1989'),
	('tt0103776', '2017-02-16 21:27:48', '2017-02-17 13:23:23', 'Michael Keaton, Danny DeVito, Michelle Pfeiffer, Christopher Walken', 'Nominated for 2 Oscars. Another 2 wins & 16 nominations.', 'USA, UK', 'Tim Burton', 'Action', '7.0', '222,333', 'English', '68', 'When a corrupt businessman and the grotesque Penguin plot to take control of Gotham City, only Batman can stop them, while the Catwoman has her own agenda.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BODM2OTc0Njg2OF5BMl5BanBnXkFtZTgwMDA4NjQxMTE@._V1_SX300.jpg', 'PG-13', '19 Jun 1992', 'True', '126 min', 'Batman Returns', 'movie', 'Bob Kane (Batman characters), Daniel Waters (story), Sam Hamm (story), Daniel Waters (screenplay)', '1992'),
	('tt0106364', '2017-02-17 13:23:28', NULL, 'Kevin Conroy, Dana Delany, Hart Bochner, Stacy Keach', '1 nomination.', 'USA', 'Eric Radomski, Bruce Timm, Kevin Altieri, Boyd Kirkland, Frank Paur, Dan Riba', 'Animation, Action, Adventure', '7.9', '30,950', 'English', 'N/A', 'Batman is wrongly implicated in a series of murders of mob bosses actually done by a new vigilante assassin.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BODE0YTBiMjQtNWQyZC00YTNjLWJmYjAtMWUwNzI4NGVlZTAzL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg', 'PG', '25 Dec 1993', 'True', '76 min', 'Batman: Mask of the Phantasm', 'movie', 'Bob Kane (character created by: Batman), Alan Burnett (story), Alan Burnett (screenplay), Paul Dini (screenplay), Martin Pasko (screenplay), Michael Reaves (screenplay)', '1993'),
	('tt0110912', '2017-02-16 16:42:58', '2017-02-16 16:43:52', 'Tim Roth, Amanda Plummer, Laura Lovelace, John Travolta', 'Won 1 Oscar. Another 60 wins & 65 nominations.', 'USA', 'Quentin Tarantino', 'Crime, Drama', '8.9', '1,376,761', 'English, Spanish, French', '94', 'The lives of two mob hit men, a boxer, a gangster\'s wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTkxMTA5OTAzMl5BMl5BanBnXkFtZTgwNjA5MDc3NjE@._V1_SX300.jpg', 'R', '14 Oct 1994', 'True', '154 min', 'Pulp Fiction', 'movie', 'Quentin Tarantino (story), Roger Avary (story), Quentin Tarantino', '1994'),
	('tt0112462', '2017-02-16 21:27:48', '2017-02-17 13:23:23', 'Val Kilmer, Tommy Lee Jones, Jim Carrey, Nicole Kidman', 'Nominated for 3 Oscars. Another 9 wins & 21 nominations.', 'USA', 'Joel Schumacher', 'Action, Adventure, Fantasy', '5.4', '196,669', 'English', '51', 'Batman must battle Two-Face and The Riddler with help from an amorous psychologist and a young circus acrobat who becomes his sidekick, Robin.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNWY3M2I0YzItNzA1ZS00MzE3LThlYTEtMTg2YjNiOTYzODQ1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'PG-13', '16 Jun 1995', 'True', '121 min', 'Batman Forever', 'movie', 'Bob Kane (characters), Lee Batchler (story), Janet Scott Batchler (story), Lee Batchler (screenplay), Janet Scott Batchler (screenplay), Akiva Goldsman (screenplay)', '1995'),
	('tt0118688', '2017-02-17 13:23:27', NULL, 'Arnold Schwarzenegger, George Clooney, Chris O\'Donnell, Uma Thurman', '10 wins & 21 nominations.', 'USA, UK', 'Joel Schumacher', 'Action, Fantasy, Sci-Fi', '3.7', '195,647', 'English', '28', 'Batman and Robin try to keep their relationship together even as they must stop Mr. Freeze and Poison Ivy from freezing Gotham City.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMGQ5YTM1NmMtYmIxYy00N2VmLWJhZTYtN2EwYTY3MWFhOTczXkEyXkFqcGdeQXVyNTA2NTI0MTY@._V1_SX300.jpg', 'PG-13', '20 Jun 1997', 'True', '125 min', 'Batman & Robin', 'movie', 'Bob Kane (Batman characters), Akiva Goldsman', '1997'),
	('tt0120744', '2017-02-16 16:59:17', '2017-02-16 17:00:10', 'Leonardo DiCaprio, Jeremy Irons, John Malkovich, Gérard Depardieu', '3 wins & 4 nominations.', 'USA, France', 'Randall Wallace', 'Action, Adventure', '6.5', '129,638', 'English, Italian', '48', 'The cruel King Louis XIV of France has a secret twin brother who he keeps imprisoned. Can the twin be substituted for the real king?', 'https://images-na.ssl-images-amazon.com/images/M/MV5BZjM2YzcxMmQtOTc2Mi00YjdhLWFlZjUtNmFmMDQzYzU2YTk5L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg', 'PG-13', '13 Mar 1998', 'True', '132 min', 'The Man in the Iron Mask', 'movie', 'Alexandre Dumas père (novels), Randall Wallace (screenplay)', '1998'),
	('tt0129167', '2017-02-16 16:59:16', '2017-02-16 17:00:10', 'Jennifer Aniston, Harry Connick Jr., Vin Diesel, James Gammon', '21 wins & 18 nominations.', 'USA', 'Brad Bird', 'Animation, Action, Adventure', '8.0', '133,190', 'English', '85', 'A young boy befriends a giant robot from outer space that a paranoid government agent wants to destroy.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjIxNDU2Njk0OV5BMl5BanBnXkFtZTgwODc3Njc3NjE@._V1_SX300.jpg', 'PG', '06 Aug 1999', 'True', '86 min', 'The Iron Giant', 'movie', 'Tim McCanlies (screenplay), Brad Bird (screen story by), Ted Hughes (based on the book "The Iron Man" by)', '1999'),
	('tt0145487', '2017-02-17 13:25:24', NULL, 'Tobey Maguire, Willem Dafoe, Kirsten Dunst, James Franco', 'Nominated for 2 Oscars. Another 14 wins & 56 nominations.', 'USA', 'Sam Raimi', 'Action, Adventure', '7.3', '562,630', 'English', '73', 'When bitten by a genetically modified spider, a nerdy, shy, and awkward high school student gains spider-like abilities that he eventually must use to fight evil as a superhero after tragedy befalls his family.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMzk3MTE5MDU5NV5BMl5BanBnXkFtZTYwMjY3NTY3._V1_SX300.jpg', 'PG-13', '03 May 2002', 'True', '121 min', 'Spider-Man', 'movie', 'Stan Lee (Marvel comic book), Steve Ditko (Marvel comic book), David Koepp (screenplay)', '2002'),
	('tt0316654', '2017-02-17 13:25:25', NULL, 'Tobey Maguire, Kirsten Dunst, James Franco, Alfred Molina', 'Won 1 Oscar. Another 23 wins & 54 nominations.', 'USA', 'Sam Raimi', 'Action, Adventure', '7.3', '428,978', 'English, Russian, Chinese', '83', 'Peter Parker is beset with troubles in his failing personal life as he battles a brilliant scientist named Doctor Otto Octavius.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMzY2ODk4NmUtOTVmNi00ZTdkLTlmOWYtMmE2OWVhNTU2OTVkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'PG-13', '30 Jun 2004', 'True', '127 min', 'Spider-Man 2', 'movie', 'Stan Lee (comic book), Steve Ditko (comic book), Alfred Gough (screen story), Miles Millar (screen story), Michael Chabon (screen story), Alvin Sargent (screenplay)', '2004'),
	('tt0371746', '2017-02-16 16:59:15', '2017-02-17 13:25:24', 'Robert Downey Jr., Terrence Howard, Jeff Bridges, Gwyneth Paltrow', 'Nominated for 2 Oscars. Another 19 wins & 61 nominations.', 'USA', 'Jon Favreau', 'Action, Adventure, Sci-Fi', '7.9', '723,653', 'English, Persian, Urdu, Arabic, Hungarian', '79', 'After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX300.jpg', 'PG-13', '02 May 2008', 'True', '126 min', 'Iron Man', 'movie', 'Mark Fergus (screenplay), Hawk Ostby (screenplay), Art Marcum (screenplay), Matt Holloway (screenplay), Stan Lee (characters), Don Heck (characters), Larry Lieber (characters), Jack Kirby (characters)', '2008'),
	('tt0372784', '2017-02-16 21:27:45', '2017-02-17 13:23:21', 'Christian Bale, Michael Caine, Liam Neeson, Katie Holmes', 'Nominated for 1 Oscar. Another 14 wins & 66 nominations.', 'USA, UK', 'Christopher Nolan', 'Action, Adventure', '8.3', '1,025,661', 'English, Urdu, Mandarin', '70', 'After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from the corruption that Scarecrow and the League of Shadows have cast upon it.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNTM3OTc0MzM2OV5BMl5BanBnXkFtZTYwNzUwMTI3._V1_SX300.jpg', 'PG-13', '15 Jun 2005', 'True', '140 min', 'Batman Begins', 'movie', 'Bob Kane (characters), David S. Goyer (story), Christopher Nolan (screenplay), David S. Goyer (screenplay)', '2005'),
	('tt0413300', '2017-02-17 13:25:25', NULL, 'Tobey Maguire, Kirsten Dunst, James Franco, Thomas Haden Church', 'Nominated for 1 BAFTA Film Award. Another 3 wins & 31 nominations.', 'USA', 'Sam Raimi', 'Action, Adventure', '6.2', '397,200', 'English, French', '59', 'A strange black entity from another world bonds with Peter Parker and causes inner turmoil as he contends with new villains, temptations, and revenge.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BYTk3MDljOWQtNGI2My00OTEzLTlhYjQtOTQ4ODM2MzUwY2IwXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg', 'PG-13', '04 May 2007', 'True', '139 min', 'Spider-Man 3', 'movie', 'Sam Raimi (screenplay), Ivan Raimi (screenplay), Alvin Sargent (screenplay), Sam Raimi (screen story), Ivan Raimi (screen story), Stan Lee (Marvel comic book), Steve Ditko (Marvel comic book)', '2007'),
	('tt0423866', '2017-02-16 16:59:48', '2017-02-16 17:00:10', 'Seung-yeon Lee, Hyun-kyoon Lee, Hyuk-ho Kwon, Jeong-ho Choi', '14 wins & 8 nominations.', 'South Korea, Japan', 'Ki-duk Kim', 'Crime, Drama, Romance', '8.1', '39,906', 'Korean', '72', 'A transient young man breaks into empty homes to partake of the vacationing residents\' lives for a few days.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTM1ODIwNzM5OV5BMl5BanBnXkFtZTcwNjk5MDkyMQ@@._V1_SX300.jpg', 'R', '15 Oct 2004', 'True', '88 min', '3-Iron', 'movie', 'Ki-duk Kim', '2004'),
	('tt0478970', '2017-02-17 13:25:25', NULL, 'Paul Rudd, Michael Douglas, Evangeline Lilly, Corey Stoll', 'Nominated for 1 BAFTA Film Award. Another 2 wins & 29 nominations.', 'USA', 'Peyton Reed', 'Action, Adventure, Comedy', '7.3', '351,580', 'English', '64', 'Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjM2NTQ5Mzc2M15BMl5BanBnXkFtZTgwNTcxMDI2NTE@._V1_SX300.jpg', 'PG-13', '17 Jul 2015', 'True', '117 min', 'Ant-Man', 'movie', 'Edgar Wright (screenplay), Joe Cornish (screenplay), Adam McKay (screenplay), Paul Rudd (screenplay), Edgar Wright (story by), Joe Cornish (story by), Stan Lee (based on the comics by), Larry Lieber (based on the comics by), Jack Kirby (based on the comics by)', '2015'),
	('tt0770828', '2017-02-17 13:25:24', NULL, 'Henry Cavill, Amy Adams, Michael Shannon, Diane Lane', '7 wins & 42 nominations.', 'USA, Canada, UK', 'Zack Snyder', 'Action, Adventure, Fantasy', '7.1', '566,423', 'English', '55', 'Clark Kent, one of the last of an extinguished race disguised as an unremarkable human, is forced to reveal his identity when Earth is invaded by an army of survivors who threaten to bring the planet to the brink of destruction.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjI5OTYzNjI0Ml5BMl5BanBnXkFtZTcwMzM1NDA1OQ@@._V1_SX300.jpg', 'PG-13', '14 Jun 2013', 'True', '143 min', 'Man of Steel', 'movie', 'David S. Goyer (screenplay), David S. Goyer (story), Christopher Nolan (story), Jerry Siegel (Superman created by), Joe Shuster (Superman created by)', '2013'),
	('tt0948470', '2017-02-17 13:25:24', NULL, 'Andrew Garfield, Emma Stone, Rhys Ifans, Denis Leary', '2 wins & 31 nominations.', 'USA', 'Marc Webb', 'Action, Adventure', '7.0', '465,391', 'English', '66', 'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to solve the mystery of his parent\'s mysterious death.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjMyOTM4MDMxNV5BMl5BanBnXkFtZTcwNjIyNzExOA@@._V1_SX300.jpg', 'PG-13', '03 Jul 2012', 'True', '136 min', 'The Amazing Spider-Man', 'movie', 'James Vanderbilt (screenplay), Alvin Sargent (screenplay), Steve Kloves (screenplay), James Vanderbilt (story), Stan Lee (based on the Marvel comic book by), Steve Ditko (based on the Marvel comic book by)', '2012'),
	('tt1007029', '2017-02-16 16:59:25', '2017-02-16 17:00:10', 'Meryl Streep, Jim Broadbent, Susan Brown, Alice da Cunha', 'Won 2 Oscars. Another 23 wins & 46 nominations.', 'UK, France', 'Phyllida Lloyd', 'Biography, Drama', '6.4', '85,076', 'English', '54', 'An elderly Margaret Thatcher talks to the imagined presence of her recently deceased husband as she struggles to come to terms with his death while scenes from her past life, from girlhood to British prime minister, intervene.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BODEzNDUyMDE3NF5BMl5BanBnXkFtZTcwMTgzOTg3Ng@@._V1_SX300.jpg', 'PG-13', '13 Jan 2012', 'True', '105 min', 'The Iron Lady', 'movie', 'Abi Morgan (screenplay)', '2011'),
	('tt1034314', '2017-02-16 16:59:33', '2017-02-16 17:00:10', 'Julia Dietze, Christopher Kirby, Götz Otto, Udo Kier', '4 wins & 2 nominations.', 'Finland, Germany, Australia', 'Timo Vuorensola', 'Action, Comedy, Sci-Fi', '5.9', '81,161', 'English, German', 'N/A', 'The Nazis set up a secret base on the dark side of the moon in 1945 where they hide out and plan to return to power in 2018.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTM2MDg5MzgxNF5BMl5BanBnXkFtZTcwODUzNjMxOA@@._V1_SX300.jpg', 'R', '04 Apr 2012', 'True', '93 min', 'Iron Sky', 'movie', 'Jarmo Puskala (original concept), Johanna Sinisalo (based on a story by), Michael Kalesniko (screenplay), Timo Vuorensola (screenplay)', '2012'),
	('tt1228705', '2017-02-16 16:59:16', '2017-02-17 13:25:24', 'Robert Downey Jr., Gwyneth Paltrow, Don Cheadle, Scarlett Johansson', 'Nominated for 1 Oscar. Another 7 wins & 40 nominations.', 'USA', 'Jon Favreau', 'Action, Adventure, Sci-Fi', '7.0', '543,285', 'English, French, Russian', '57', 'With the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful mad man with ties to his father\'s legacy.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTM0MDgwNjMyMl5BMl5BanBnXkFtZTcwNTg3NzAzMw@@._V1_SX300.jpg', 'PG-13', '07 May 2010', 'True', '124 min', 'Iron Man 2', 'movie', 'Justin Theroux (screenplay), Stan Lee (Marvel comic book), Don Heck (Marvel comic book), Larry Lieber (Marvel comic book), Jack Kirby (Marvel comic book)', '2010'),
	('tt1258972', '2017-02-16 16:59:39', '2017-02-16 17:00:10', 'RZA, Rick Yune, Russell Crowe, Lucy Liu', '3 nominations.', 'USA, Hong Kong', 'RZA', 'Action', '5.4', '54,410', 'English, Mandarin', '51', 'On the hunt for a fabled treasure of gold, a band of warriors, assassins, and a rogue British soldier descend upon a village in feudal China, where a humble blacksmith looks to defend himself and his fellow villagers.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTg5ODI3ODkzOV5BMl5BanBnXkFtZTcwMTQxNjUwOA@@._V1_SX300.jpg', 'R', '02 Nov 2012', 'True', '95 min', 'The Man with the Iron Fists', 'movie', 'RZA (story), RZA (screenplay), Eli Roth (screenplay)', '2012'),
	('tt1300854', '2017-02-16 16:59:16', '2017-02-17 13:25:24', 'Robert Downey Jr., Gwyneth Paltrow, Don Cheadle, Guy Pearce', 'Nominated for 1 Oscar. Another 17 wins & 53 nominations.', 'USA', 'Shane Black', 'Action, Adventure, Sci-Fi', '7.2', '574,910', 'English', '62', 'When Tony Stark\'s world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTkzMjEzMjY1M15BMl5BanBnXkFtZTcwNTMxOTYyOQ@@._V1_SX300.jpg', 'PG-13', '03 May 2013', 'True', '130 min', 'Iron Man 3', 'movie', 'Drew Pearce (screenplay), Shane Black (screenplay), Stan Lee (based on the Marvel comic book by), Don Heck (based on the Marvel comic book by), Larry Lieber (based on the Marvel comic book by), Jack Kirby (based on the Marvel comic book by), Warren Ellis (based on the "Extremis" mini-series written by), Adi Granov (based on the "Extremis" mini-series illustrated by)', '2013'),
	('tt1569923', '2017-02-17 13:23:28', NULL, 'Bruce Greenwood, Jensen Ackles, John DiMaggio, Neil Patrick Harris', '1 nomination.', 'USA', 'Brandon Vietti', 'Animation, Action, Crime', '8.1', '40,076', 'English', 'N/A', 'There\'s a mystery afoot in Gotham City, and Batman must go toe-to-toe with a mysterious vigilante, who goes by the name of Red Hood. Subsequently, old wounds reopen and old, once buried memories come into the light.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BYTdlODI0YTYtNjk5ZS00YzZjLTllZjktYmYzNWM4NmI5MmMxXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg', 'PG-13', '27 Jul 2010', 'True', '75 min', 'Batman: Under the Red Hood', 'movie', 'Judd Winick, Bob Kane (Batman created by)', '2010'),
	('tt1826885', '2017-02-17 13:24:56', NULL, 'Aaron Bannister, Ian Cawley, Sami Elnasser, Elyssa Grant', 'N/A', 'USA', 'Dylan Stipek, Jesse Stipek, Miles Stipek', 'Short', 'N/A', 'N/A', 'English', 'N/A', 'Based on Medieval folklore, this short film is about an ailing boy named Aron who is on a mission to discover a cure to his illness. He is a bright and ambitious individual, but later runs ...', 'http://ia.media-imdb.com/images/M/MV5BMTkzMjQzMjc0MV5BMl5BanBnXkFtZTcwMzE3NTY0NA@@._V1_SX300.jpg', 'N/A', '01 Feb 2011', 'True', '13 min', 'The Allegory of Aron Godfrey', 'movie', 'Jesse Stipek (story)', '2011'),
	('tt2166834', '2017-02-17 13:23:28', NULL, 'Peter Weller, Ariel Winter, Michael Emerson, David Selby', '1 win & 1 nomination.', 'USA', 'Jay Oliva', 'Animation, Action, Crime', '8.4', '33,262', 'English', 'N/A', 'The Batman has returned after a 10-year absence. The Gotham authorities want to arrest him. An old foe wants a reunion. The Feds want the Man of Tomorrow to put a stop to him.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ1Mjk1NTY2NV5BMl5BanBnXkFtZTgwMTA2MDEwNzE@._V1_SX300.jpg', 'PG-13', '29 Jan 2013', 'True', '76 min', 'Batman: The Dark Knight Returns, Part 2', 'movie', 'Bob Kane (character created by: Batman), Jerry Siegel (character created by: Superman), Joe Shuster (character created by: Superman), Frank Miller (comic book), Klaus Janson (comic book), Bob Goodman', '2013'),
	('tt2313197', '2017-02-17 13:23:28', NULL, 'Peter Weller, Ariel Winter, David Selby, Wade Williams', '5 nominations.', 'USA', 'Jay Oliva', 'Animation, Action, Adventure', '8.0', '39,257', 'English', 'N/A', 'Batman has not been seen for ten years. A new breed of criminal ravages Gotham City, forcing 55-year-old Bruce Wayne back into the cape and cowl. But, does he still have what it takes to fight crime in a new era?', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMzIxMDkxNDM2M15BMl5BanBnXkFtZTcwMDA5ODY1OQ@@._V1_SX300.jpg', 'PG-13', '25 Sep 2012', 'True', '76 min', 'Batman: The Dark Knight Returns, Part 1', 'movie', 'Bob Kane (character created by: Batman), Frank Miller (comic book), Klaus Janson (comic book), Bob Goodman', '2012'),
	('tt2975590', '2017-02-16 13:06:06', '2017-02-17 13:23:23', 'Ben Affleck, Henry Cavill, Amy Adams, Jesse Eisenberg', '4 wins & 21 nominations.', 'USA', 'Zack Snyder', 'Action, Adventure, Sci-Fi', '6.7', '448,772', 'English', '44', 'Fearing that the actions of Superman are left unchecked, Batman takes on the Man of Steel, while the world wrestles with what kind of a hero it really needs.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BYThjYzcyYzItNTVjNy00NDk0LTgwMWQtYjMwNmNlNWJhMzMyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'PG-13', '25 Mar 2016', 'True', '151 min', 'Batman v Superman: Dawn of Justice', 'movie', 'Chris Terrio, David S. Goyer, Bob Kane (Batman created by), Bill Finger (Batman created by), Jerry Siegel (Superman created by), Joe Shuster (Superman created by)', '2016'),
	('tt3727758', '2017-02-16 13:06:09', '2017-02-16 15:48:02', 'N/A', 'N/A', 'USA', 'N/A', 'Action', 'N/A', 'N/A', 'N/A', 'N/A', 'The caped crusader is reborn.', 'N/A', 'N/A', 'N/A', 'True', 'N/A', 'Batman Infinite', 'movie', 'N/A', '2016'),
	('tt4315274', '2017-02-16 14:33:38', '2017-02-16 15:27:04', 'Mallory Wetton', 'N/A', 'USA', 'Kevin Wong', 'Documentary, Short', 'N/A', 'N/A', 'English', 'N/A', 'The 1964 World\'s Fair in New York: a modern event of postwar progress. While the Ford Mustang made its debut and American companies boasted of their new technology, a class of subway cars ...', 'N/A', 'N/A', 'N/A', 'True', 'N/A', 'On the Wings of the Blue Arrow', 'movie', 'Kevin Wong', '2016'),
	('tt4430982', '2017-02-16 13:06:09', '2017-02-16 15:48:02', 'James Spiering, Stephanie Desiree Huebner, Tyler Denn, West Christy', 'N/A', 'USA', 'Liam Galey', 'Action', 'N/A', 'N/A', 'English', 'N/A', 'Set 40 years after the attempted destruction of Gotham by Bane, the city of Gotham has been shut down by the U.S. Government and the people of Gotham and its crime have been moved to cities...', 'N/A', 'N/A', 'N/A', 'True', 'N/A', 'Batman: The Dark Knight Beyond', 'movie', 'Justin Blasdel, James Spiering', '2016'),
	('tt4853102', '2017-02-16 13:06:07', '2017-02-16 15:48:01', 'Kevin Conroy, Mark Hamill, Tara Strong, Ray Wise', 'N/A', 'USA', 'Sam Liu', 'Animation, Action, Crime', '6.5', '30,801', 'English', 'N/A', 'As Batman hunts for the escaped Joker, the Clown Prince of Crime attacks the Gordon family to prove a diabolical point mirroring his own fall into madness.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BODcxYTc5NmQtZTZjNS00MjRiLTgxMjQtN2VhYjY2YjdmMzYzXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg', 'R', '25 Jul 2016', 'True', '76 min', 'Batman: The Killing Joke', 'movie', 'Brian Azzarello, Brian Bolland (based on the graphic novel illustrated by), Bob Kane (Batman created by), Bill Finger (Batman created by)', '2016'),
	('tt4870838', '2017-02-16 13:06:07', '2017-02-16 15:48:01', 'Jason O\'Mara, Yvonne Strahovski, Stuart Allan, Sean Maher', 'N/A', 'USA', 'Jay Oliva', 'Animation, Action, Adventure', '6.8', '10,604', 'English', 'N/A', 'Bruce Wayne is missing. Alfred covers for him while Nightwing and Robin patrol Gotham City in his stead. And a new player, Batwoman, investigates Batman\'s disappearance.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BZWZiZmZhYmQtYjVkZi00MWIzLWEzM2MtYzhkNjliNzc2MTMwL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg', 'PG-13', '19 Jan 2016', 'True', '72 min', 'Batman: Bad Blood', 'movie', 'J.M. DeMatteis, Bob Kane (character created by: Batman), Doug Moench (character created by: Black Mask), Tom Mandrake (character created by: Black Mask), Len Wein (character created by: Lucius Fox), John Calnan (character created by: Lucius Fox), Marv Wolfman (character created by: Nightwing), George Pérez (character created by: Nightwing), Denny O\'Neil (character created by: Talia al Ghul)', '2016'),
	('tt5276352', '2017-02-16 14:33:38', '2017-02-16 15:27:04', 'Toby Nichols, Benjamin Wood, Alicia Davis Johnson, Brad Beall', 'N/A', 'USA', 'Christian Walker', 'Short, Biography, Drama', 'N/A', 'N/A', 'English', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'True', 'N/A', 'Arrow of Light', 'movie', 'Randal O\'Wain, Christian Walker', '2016'),
	('tt5466692', '2017-02-16 14:33:37', '2017-02-16 15:27:02', 'Kris Rowberry', 'N/A', 'USA', 'Nicholas Laschkewitsch', 'Documentary', '8.2', '10', 'English', 'N/A', 'The rise and fall of one of America\'s major roller coaster manufacturers.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BODIzNmRlODctNjYyOS00NTM2LWFkYTgtYzRmNmY3NTk2YTk5XkEyXkFqcGdeQXVyNjU0MzIyNjg@._V1_SX300.jpg', 'N/A', '26 Feb 2016', 'True', 'N/A', 'The Legacy of Arrow Development', 'movie', 'Kris Rowberry', '2016'),
	('tt5479456', '2017-02-16 14:33:38', '2017-02-16 15:27:03', 'Dante DeAntonio, Nick Bennie, Josh Bidwell, Timmy Griffin', 'N/A', 'USA', 'Ian Michael Lewis', 'Action', 'N/A', 'N/A', 'English', 'N/A', 'After The Riddler leads Batman to Star City, he must unite with a fellow vigilante, The Arrow, but the two do not see eye to eye.', 'N/A', 'N/A', '01 Jan 2016', 'True', '60 min', 'Batman V Arrow', 'movie', 'Dante DeAntonio (screenplay), Bill Finger (character created by: Batman), Marc Guggenheim (written and developed for television by: Arrow), Bob Kane (character created by: Batman), Ian Michael Lewis (screenplay), Mort Weisinger (character created by: Green Arrow)', '2016'),
	('tt5492852', '2017-02-16 14:33:38', '2017-02-16 15:27:03', 'Anna Katharina Haukeland', 'N/A', 'Norway', 'Camilla Figenschou', 'N/A', 'N/A', 'N/A', 'Norwegian', 'N/A', 'N/A', 'N/A', 'N/A', '22 Jan 2016', 'True', 'N/A', 'Bow and Arrow', 'movie', 'Camilla Figenschou (screen writer)', '2016'),
	('tt5708320', '2017-02-16 15:57:44', NULL, 'Victoria Allen, Ashley Anderson, Luis Arana, Gail Arco', 'N/A', 'USA', 'Jamal Johns', 'Sci-Fi', '8.2', '10', 'English', 'N/A', 'A what if story set in the Detective Comics Universe.', 'http://ia.media-imdb.com/images/M/MV5BNWVlNDA4MGUtNWZiMS00Mjk0LThmZmQtZDc2YmQ3NGE5NDQ3XkEyXkFqcGdeQXVyNjA3MDUwNjQ@._V1_SX300.jpg', 'N/A', '25 Apr 2016', 'True', '44 min', 'Dark Superman', 'movie', 'Luis Delgado, Jamal Johns', '2016'),
	('tt5820860', '2017-02-16 15:58:02', NULL, 'Tash Cox, Sasha Travis, Steve Kefalas, Gordon Bash', 'N/A', 'USA', 'Jean Renard', 'Short, Music', 'N/A', 'N/A', 'English', 'N/A', 'N/A', 'http://ia.media-imdb.com/images/M/MV5BZDI3M2RiNTEtMzM1Yi00ZGQwLTg1YWUtZTBkOTk4NDc1ZmIzXkEyXkFqcGdeQXVyNDY2NzI5NjQ@._V1_SX300.jpg', 'N/A', '17 Jun 2016', 'True', '5 min', 'Alice Underground: Superman', 'movie', 'N/A', '2016'),
	('tt5845956', '2017-02-16 13:06:08', '2017-02-16 15:48:02', 'Robert P. Young, Zack Santiago, Emily Rhoads, Robert Paterson', 'N/A', 'USA', 'Chris R. Notarile', 'Short, Action, Crime', '4.5', '13', 'English', 'N/A', 'As told through the eyes of a heroin addict, a homeless man, named Dante, witnesses Gotham\'s Dark Knight stop a crime, but what he sees is terrifying beyond even his own comprehension.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BYjVkODhlNjUtNTY1MC00Yjg0LTkyOTUtZGJlOWQ1Yzg1Y2ZiXkEyXkFqcGdeQXVyMTg1MTc3MQ@@._V1_SX300.jpg', 'N/A', '05 Aug 2016', 'True', '10 min', 'Batman: Dante', 'movie', 'Bill Finger (creator), Bob Kane (creator), Chris R. Notarile', '2016'),
	('tt5852184', '2017-02-16 15:58:20', NULL, 'Keith Stahle, Janelle Giebel, Kevin Staley, Lisa Horacek', 'N/A', 'USA', 'Keith Stahle', 'Short, Action', 'N/A', 'N/A', 'English', 'N/A', 'The Joker neutralizes Superman\'s powers. Now Bane and Superman must now fight to the death as Clark\'s high school sweet heart Lana Lang is captive - her life hanging in the balance.', 'N/A', 'N/A', '01 Jul 2016', 'True', 'N/A', 'Bane v Superman: The Movie', 'movie', 'Keith Stahle', '2016'),
	('tt5867864', '2017-02-16 15:58:36', NULL, 'Hiram A. Murray, Miggs Cuaderno, Anne Gauthier, Ruby Ruiz', 'N/A', 'USA', 'Ethan Page', 'Short, Comedy', 'N/A', 'N/A', 'English', 'N/A', 'A trip to the Philippines sets a US Marine on the path to love and disaster.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMzM2M2RlNDQtNzlhNi00NzRiLTliMTctOTcwZTFjNjRiMzgyXkEyXkFqcGdeQXVyMjY4MzQ3NTg@._V1_SX300.jpg', 'N/A', 'N/A', 'True', 'N/A', 'Black Superman', 'movie', 'Ethan Page', '2016'),
	('tt5875708', '2017-02-16 13:06:08', '2017-02-16 15:48:02', 'Michael Calkins, John Calkins, Tony Calkins, Michael Consalvo', 'N/A', 'USA', 'Tony Calkins', 'Comedy', '8.7', '7', 'English', 'N/A', 'Your favorite dynamic duo is back and crazier than ever! Follow 1960\'s styled Batman and Robin on their mission to bust a drug lord and a few of their classic enemies.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNjdhZjM0NGYtMjgxOC00NTkxLTg1ZTEtMjZhNDhjYjZjMjFlXkEyXkFqcGdeQXVyMjQ5MDAyNzc@._V1_SX300.jpg', 'N/A', '12 Mar 2016', 'True', 'N/A', 'B@ (Batman Parody Film)', 'movie', 'Tony Calkins', '2016'),
	('tt5891480', '2017-02-16 14:33:38', '2017-02-16 15:27:03', 'N/A', 'N/A', 'USA', 'Christian Walker', 'Short, Drama, Family', 'N/A', 'N/A', 'English', 'N/A', 'Following the suicide of his best friend, a grieving father brings his two young boys along to pay a grisly, but sweet homage', 'N/A', 'N/A', 'N/A', 'True', '20 min', 'Arrow of Light', 'movie', 'N/A', '2016'),
	('tt5896146', '2017-02-16 13:06:08', '2017-02-16 15:48:02', 'Carlos Alazraqui, Troy Baker, Chris Diamantopoulos, John DiMaggio', 'N/A', 'USA', 'Curt Geda', 'Animation, Action, Sci-Fi', '5.8', '536', 'English', 'N/A', 'The Dark Knight is back doing what he does best - protecting the citizens of Gotham City - in the third installment of the Batman Unlimited series, Batman Unlimited: Mechs vs. Mutants. When...', 'https://images-na.ssl-images-amazon.com/images/M/MV5BZWVhZTNmZTQtZTgwYS00YWE5LThjMjktMjFkNjEwYzdkODA2XkEyXkFqcGdeQXVyNDM1NDAyNDk@._V1_SX300.jpg', 'N/A', '30 Aug 2016', 'True', '72 min', 'Batman Unlimited: Mechs vs. Mutants', 'movie', 'Kevin Burke, Chris Wyatt', '2016'),
	('tt5916942', '2017-02-16 15:58:51', NULL, 'Amy Adams, Henry Cavill, Geoff Johns, Zack Snyder', 'N/A', 'USA', 'N/A', 'Documentary, Short', 'N/A', 'N/A', 'English', 'N/A', 'A refresher course on the incarnation of Superman first introduced in Man of Steel, plus a look at his redesigned costume.', 'N/A', 'N/A', '19 Jul 2016', 'True', '7 min', 'Superman: Complexity & Truth', 'movie', 'N/A', '2016'),
	('tt5953262', '2017-02-16 15:59:08', NULL, 'Mark David Christenson, Jen Krueger', 'N/A', 'USA', 'Will Reese', 'Short, Drama', 'N/A', 'N/A', 'English', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'True', '8 min', 'Good Morning, Superman', 'movie', 'Mark David Christenson', '2016'),
	('tt5973626', '2017-02-16 13:06:07', '2017-02-16 15:48:01', 'Adam West, Burt Ward, Julie Newmar, Jeff Bergman', '1 nomination.', 'USA', 'Rick Morales', 'Animation, Action, Adventure', '7.0', '1,924', 'English', 'N/A', 'Batman and Robin are back in action to take down their fiendish foes once again with original actors Adam West voicing Batman, Burt Ward voicing Robin, and Julie Newmar voicing Catwoman.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BYzg0MmNlOTMtNTY3Yi00NmJhLWFjMWUtNzkzNzJjMDk2ZmJlXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg', 'PG', '11 Oct 2016', 'True', '78 min', 'Batman: Return of the Caped Crusaders', 'movie', 'Michael Jelenic (screenplay), James Tucker (screenplay), William Dozier (based on the 1966 Batman series created by), Bob Kane (character created by: Batman), Bill Finger (character created by: Batman)', '2016'),
	('tt5988932', '2017-02-16 13:06:09', '2017-02-16 15:48:02', 'Bryce Kelly, Mathew Lar, Michael Towns, Mike A. Towns', 'N/A', 'USA', 'Max Litinsmeyer', 'Short, Action', 'N/A', 'N/A', 'English', 'N/A', 'Richard Grayson has had 8 years of being robin and gets ready to be on his own', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjVjZTY0MWUtZGE3Ny00MWQ2LWE4N2QtMDkyYzI1NTc1M2YxXkEyXkFqcGdeQXVyNjgyMjM1NTc@._V1_SX300.jpg', 'N/A', '13 Oct 2016', 'True', 'N/A', 'Batman the Dawn of the Knight', 'movie', 'Max Litinsmeyer', '2016'),
	('tt6051984', '2017-02-16 15:59:25', NULL, 'James Keanu Reichel, Jay Ramiscal, Phil Tamboa, Grace Chee', 'N/A', 'USA', 'Keoni Maemori', 'Short, Action', 'N/A', 'N/A', 'English', 'N/A', 'N/A', 'N/A', 'N/A', '06 Jun 2016', 'True', '3 min', 'Batman vs. Superman Hawaii', 'movie', 'Keoni Maemori', '2016'),
	('tt6107910', '2017-02-16 15:59:44', NULL, 'Pete Bune, Jaime Fernandez, Missy Moser, Jim Shearer', 'N/A', 'USA', 'Pete Bune', 'Animation, Short', 'N/A', 'N/A', 'English', 'N/A', 'Superman has no problem with being the Savior of Metropolis, but when a small group of people show their appreciation by starting a "Church of the Son of Krypton", Clark Kent himself is at ...', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNjNkZTQxM2YtOGJmOC00YTAwLWJmZWItNmFkMzZhMWExZWYxXkEyXkFqcGdeQXVyNjg4NjEzMw@@._V1_SX300.jpg', 'N/A', '24 Oct 2016', 'True', 'N/A', 'Church of Superman', 'movie', 'Pete Bune', '2016'),
	('tt6159030', '2017-02-16 16:00:01', NULL, 'Nic Davidson, J.R. Meehl', 'N/A', 'USA', 'Woody Smith', 'Short, Action', 'N/A', 'N/A', 'English', 'N/A', 'Who has the better superpower? Batman? Superman? Find out by watching.', 'https://images-na.ssl-images-amazon.com/images/M/MV5BYThjYzcyYzItNTVjNy00NDk0LTgwMWQtYjMwNmNlNWJhMzMyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'N/A', '17 Oct 2016', 'True', '6 min', 'Batman vs Superman: The Best Superpower Ever', 'movie', 'Nic Davidson, J.R. Meehl, Woody Smith (creator)', '2016'),
	('tt6446760', '2017-02-16 14:33:38', '2017-02-16 15:27:03', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', '18 Sep 2016', 'True', 'N/A', 'Silk Road Hero: Khan\'s Arrow', 'movie', 'N/A', '2016');
/*!40000 ALTER TABLE `movie` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
